#docker-compose.yml
version: '2'

services:    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      LIMIT_MAXIMUM_TIME: "01:00:00" # save channel every 30 minutes with "00:30:00"
      COMMAND_ADAPTER: 'ShellAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chaturbate-recorder'
      USER_ID: 0
      USER_GID: 0
    volumes:
      - /Users/christianknedel/videos:/code/database
      - ./interface/logs:/code/logs
      - /Users/christianknedel/videos:/code/videos
    ports:
      - "8002:8000"
