version: '2'

services:    
  app:
    image: chrisknedel/chatrubate-recorder-gui:1.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      ABSOLUTE_HOST_MEDIA: "/Users/christianknedel/videos/"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOCKER_CONTAINER: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'DockerAdapter' #For Kubernetes 'KubernetesAdapter'
      CONTAINER_PREFFIX: 'cr_'
      RECORDER_IMAGE: 'chrisknedel/chatrubate-recorder:1.0'
      USER_UID: 0
      USER_GID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/christianknedel/videos:/code/database
      - ./logs:/code/logs
    ports:
      - "8002:8000"
