#docker-compose.yml
version: '2'

services:    
  app:
    image: chrisknedel/chatrubate-recorder-gui:2.0
    container_name: recorder_app
    restart: always
    environment:
      TZ: "Europe/Berlin"
      LIMIT_MAXIMUM_FOLDER_GB: 20 #or "0" to disable this limit
      LIMIT_MAXIMUM_DOWNLOADS: 10 #or "0" to disable this limit
      COMMAND_ADAPTER: 'ShellAdapter'
      CONTAINER_PREFFIX: 'cr_'
      USER_ID: 0
      USER_GID: 0
    volumes:
      - /Users/christianknedel/videos:/code/database
      - /Users/christianknedel/videos:/code/videos
    ports:
      - "8002:8000"

